# -*- coding: utf-8 -*-
"""Blackcoffer_Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oONcJE-BhFXx9Ii7xMu2oMcPwPnaOqL2
"""

import requests
from bs4 import BeautifulSoup

# URL of the article
url = "https://insights.blackcoffer.com/rise-of-telemedicine-and-its-impact-on-livelihood-by-2040-3-2/"

# Send a GET request to the URL
response = requests.get(url)
html_content = response.content

# Create a BeautifulSoup object
soup = BeautifulSoup(html_content, 'html.parser')

# Find the main article content by inspecting the HTML structure
article_content = soup.find('div', class_='td-post-content')

# Extract and print the article text
if article_content:
    paragraphs = article_content.find_all('p')
    article_text = "\n".join([p.get_text() for p in paragraphs])
    print(article_text)
else:
    print("Article content not found on the page.")

urls = ['https://insights.blackcoffer.com/rise-of-telemedicine-and-its-impact-on-livelihood-by-2040-3-2/',
'https://insights.blackcoffer.com/rise-of-e-health-and-its-impact-on-humans-by-the-year-2030/',
'https://insights.blackcoffer.com/rise-of-e-health-and-its-imapct-on-humans-by-the-year-2030-2/',
'https://insights.blackcoffer.com/rise-of-telemedicine-and-its-impact-on-livelihood-by-2040-2/',
'https://insights.blackcoffer.com/rise-of-telemedicine-and-its-impact-on-livelihood-by-2040-2-2/',
'https://insights.blackcoffer.com/rise-of-chatbots-and-its-impact-on-customer-support-by-the-year-2040/',
'https://insights.blackcoffer.com/rise-of-e-health-and-its-imapct-on-humans-by-the-year-2030/',
'https://insights.blackcoffer.com/how-does-marketing-influence-businesses-and-consumers/',
'https://insights.blackcoffer.com/how-advertisement-increase-your-market-value/',
'https://insights.blackcoffer.com/negative-effects-of-marketing-on-society/',
'https://insights.blackcoffer.com/how-advertisement-marketing-affects-business/',
'https://insights.blackcoffer.com/rising-it-cities-will-impact-the-economy-environment-infrastructure-and-city-life-by-the-year-2035/',
'https://insights.blackcoffer.com/rise-of-ott-platform-and-its-impact-on-entertainment-industry-by-the-year-2030/',
'https://insights.blackcoffer.com/rise-of-electric-vehicles-and-its-impact-on-livelihood-by-2040/',
'https://insights.blackcoffer.com/rise-of-electric-vehicle-and-its-impact-on-livelihood-by-the-year-2040/',
'https://insights.blackcoffer.com/oil-prices-by-the-year-2040-and-how-it-will-impact-the-world-economy/',
'https://insights.blackcoffer.com/an-outlook-of-healthcare-by-the-year-2040-and-how-it-will-impact-human-lives/',
'https://insights.blackcoffer.com/ai-in-healthcare-to-improve-patient-outcomes/',
'https://insights.blackcoffer.com/what-if-the-creation-is-taking-over-the-creator/',
'https://insights.blackcoffer.com/what-jobs-will-robots-take-from-humans-in-the-future/',
'https://insights.blackcoffer.com/will-machine-replace-the-human-in-the-future-of-work/',
'https://insights.blackcoffer.com/will-ai-replace-us-or-work-with-us/',
'https://insights.blackcoffer.com/man-and-machines-together-machines-are-more-diligent-than-humans-blackcoffe/',
'https://insights.blackcoffer.com/in-future-or-in-upcoming-years-humans-and-machines-are-going-to-work-together-in-every-field-of-work/',
'https://insights.blackcoffer.com/how-neural-networks-can-be-applied-in-various-areas-in-the-future/',
'https://insights.blackcoffer.com/how-machine-learning-will-affect-your-business/',
'https://insights.blackcoffer.com/deep-learning-impact-on-areas-of-e-learning/',
'https://insights.blackcoffer.com/how-to-protect-future-data-and-its-privacy-blackcoffer/',
'https://insights.blackcoffer.com/how-machines-ai-automations-and-robo-human-are-effective-in-finance-and-banking/',
'https://insights.blackcoffer.com/ai-human-robotics-machine-future-planet-blackcoffer-thinking-jobs-workplace/',
'https://insights.blackcoffer.com/how-ai-will-change-the-world-blackcoffer/',
'https://insights.blackcoffer.com/future-of-work-how-ai-has-entered-the-workplace/',
'https://insights.blackcoffer.com/ai-tool-alexa-google-assistant-finance-banking-tool-future/',
'https://insights.blackcoffer.com/ai-healthcare-revolution-ml-technology-algorithm-google-analytics-industrialrevolution/',
'https://insights.blackcoffer.com/all-you-need-to-know-about-online-marketing/',
'https://insights.blackcoffer.com/evolution-of-advertising-industry/',
'https://insights.blackcoffer.com/how-data-analytics-can-help-your-business-respond-to-the-impact-of-covid-19/',
'https://insights.blackcoffer.com/covid-19-environmental-impact-for-the-future/',
'https://insights.blackcoffer.com/environmental-impact-of-the-covid-19-pandemic-lesson-for-the-future/',
'https://insights.blackcoffer.com/how-data-analytics-and-ai-are-used-to-halt-the-covid-19-pandemic/',
'https://insights.blackcoffer.com/difference-between-artificial-intelligence-machine-learning-statistics-and-data-mining/',
'https://insights.blackcoffer.com/how-python-became-the-first-choice-for-data-science/',
'https://insights.blackcoffer.com/how-google-fit-measure-heart-and-respiratory-rates-using-a-phone/',
'https://insights.blackcoffer.com/what-is-the-future-of-mobile-apps/',
'https://insights.blackcoffer.com/impact-of-ai-in-health-and-medicine/',
'https://insights.blackcoffer.com/telemedicine-what-patients-like-and-dislike-about-it/',
'https://insights.blackcoffer.com/how-we-forecast-future-technologies/',
'https://insights.blackcoffer.com/can-robots-tackle-late-life-loneliness/',
'https://insights.blackcoffer.com/embedding-care-robots-into-society-socio-technical-considerations/',
'https://insights.blackcoffer.com/management-challenges-for-future-digitalization-of-healthcare-services/',
'https://insights.blackcoffer.com/are-we-any-closer-to-preventing-a-nuclear-holocaust/',
'https://insights.blackcoffer.com/will-technology-eliminate-the-need-for-animal-testing-in-drug-development/',
'https://insights.blackcoffer.com/will-we-ever-understand-the-nature-of-consciousness/',
'https://insights.blackcoffer.com/will-we-ever-colonize-outer-space/',
'https://insights.blackcoffer.com/what-is-the-chance-homo-sapiens-will-survive-for-the-next-500-years/',
'https://insights.blackcoffer.com/why-does-your-business-need-a-chatbot/',
'https://insights.blackcoffer.com/how-you-lead-a-project-or-a-team-without-any-technical-expertise/',
'https://insights.blackcoffer.com/can-you-be-great-leader-without-technical-expertise/',
'https://insights.blackcoffer.com/how-does-artificial-intelligence-affect-the-environment/',
'https://insights.blackcoffer.com/how-to-overcome-your-fear-of-making-mistakes-2/',
'https://insights.blackcoffer.com/is-perfection-the-greatest-enemy-of-productivity/',
'https://insights.blackcoffer.com/global-financial-crisis-2008-causes-effects-and-its-solution/',
'https://insights.blackcoffer.com/gender-diversity-and-equality-in-the-tech-industry/',
'https://insights.blackcoffer.com/how-to-overcome-your-fear-of-making-mistakes/',
'https://insights.blackcoffer.com/how-small-business-can-survive-the-coronavirus-crisis/',
'https://insights.blackcoffer.com/impacts-of-covid-19-on-vegetable-vendors-and-food-stalls/',
'https://insights.blackcoffer.com/impacts-of-covid-19-on-vegetable-vendors/',
'https://insights.blackcoffer.com/impact-of-covid-19-pandemic-on-tourism-aviation-industries/',
'https://insights.blackcoffer.com/impact-of-covid-19-pandemic-on-sports-events-around-the-world/',
'https://insights.blackcoffer.com/changing-landscape-and-emerging-trends-in-the-indian-it-ites-industry/',
'https://insights.blackcoffer.com/online-gaming-adolescent-online-gaming-effects-demotivated-depression-musculoskeletal-and-psychosomatic-symptoms/',
'https://insights.blackcoffer.com/human-rights-outlook/',
'https://insights.blackcoffer.com/how-voice-search-makes-your-business-a-successful-business/',
'https://insights.blackcoffer.com/how-the-covid-19-crisis-is-redefining-jobs-and-services/',
'https://insights.blackcoffer.com/how-to-increase-social-media-engagement-for-marketers/',
'https://insights.blackcoffer.com/impacts-of-covid-19-on-streets-sides-food-stalls/',
'https://insights.blackcoffer.com/coronavirus-impact-on-energy-markets-2/',
'https://insights.blackcoffer.com/coronavirus-impact-on-the-hospitality-industry-5/',
'https://insights.blackcoffer.com/lessons-from-the-past-some-key-learnings-relevant-to-the-coronavirus-crisis-4/',
'https://insights.blackcoffer.com/estimating-the-impact-of-covid-19-on-the-world-of-work-2/',
'https://insights.blackcoffer.com/estimating-the-impact-of-covid-19-on-the-world-of-work-3/',
'https://insights.blackcoffer.com/travel-and-tourism-outlook/',
'https://insights.blackcoffer.com/gaming-disorder-and-effects-of-gaming-on-health/',
'https://insights.blackcoffer.com/what-is-the-repercussion-of-the-environment-due-to-the-covid-19-pandemic-situation/',
'https://insights.blackcoffer.com/what-is-the-repercussion-of-the-environment-due-to-the-covid-19-pandemic-situation-2/',
'https://insights.blackcoffer.com/impact-of-covid-19-pandemic-on-office-space-and-co-working-industries/',
'https://insights.blackcoffer.com/contribution-of-handicrafts-visual-arts-literature-in-the-indian-economy/',
'https://insights.blackcoffer.com/how-covid-19-is-impacting-payment-preferences/',
'https://insights.blackcoffer.com/how-will-covid-19-affect-the-world-of-work-2/',
'https://insights.blackcoffer.com/lessons-from-the-past-some-key-learnings-relevant-to-the-coronavirus-crisis/',
'https://insights.blackcoffer.com/covid-19-how-have-countries-been-responding/',
'https://insights.blackcoffer.com/coronavirus-impact-on-the-hospitality-industry-2/',
'https://insights.blackcoffer.com/how-will-covid-19-affect-the-world-of-work-3/',
'https://insights.blackcoffer.com/coronavirus-impact-on-the-hospitality-industry-3/',
'https://insights.blackcoffer.com/estimating-the-impact-of-covid-19-on-the-world-of-work/',
'https://insights.blackcoffer.com/covid-19-how-have-countries-been-responding-2/',
'https://insights.blackcoffer.com/how-will-covid-19-affect-the-world-of-work-4/',
'https://insights.blackcoffer.com/lessons-from-the-past-some-key-learnings-relevant-to-the-coronavirus-crisis-2/',
'https://insights.blackcoffer.com/lessons-from-the-past-some-key-learnings-relevant-to-the-coronavirus-crisis-3/',
'https://insights.blackcoffer.com/coronavirus-impact-on-the-hospitality-industry-4/',
'https://insights.blackcoffer.com/why-scams-like-nirav-modi-happen-with-indian-banks/',
'https://insights.blackcoffer.com/impact-of-covid-19-on-the-global-economy/',
'https://insights.blackcoffer.com/impact-of-covid-19coronavirus-on-the-indian-economy-2/',
'https://insights.blackcoffer.com/impact-of-covid-19-on-the-global-economy-2/',
'https://insights.blackcoffer.com/impact-of-covid-19-coronavirus-on-the-indian-economy-3/',
'https://insights.blackcoffer.com/should-celebrities-be-allowed-to-join-politics/',
'https://insights.blackcoffer.com/how-prepared-is-india-to-tackle-a-possible-covid-19-outbreak/',
'https://insights.blackcoffer.com/how-will-covid-19-affect-the-world-of-work/',
'https://insights.blackcoffer.com/controversy-as-a-marketing-strategy/',
'https://insights.blackcoffer.com/coronavirus-impact-on-the-hospitality-industry/',
'https://insights.blackcoffer.com/coronavirus-impact-on-energy-markets/',
'https://insights.blackcoffer.com/what-are-the-key-policies-that-will-mitigate-the-impacts-of-covid-19-on-the-world-of-work/',
'https://insights.blackcoffer.com/marketing-drives-results-with-a-focus-on-problems/',
'https://insights.blackcoffer.com/continued-demand-for-sustainability/'

        ]

import os
import requests
from bs4 import BeautifulSoup

# Create a directory to store the text files
output_directory = "scraped_data"
os.makedirs(output_directory, exist_ok=True)

# Loop through each URL
for url in urls:
    response = requests.get(url)
    html_content = response.content
    soup = BeautifulSoup(html_content, 'html.parser')

    # Find the main article content
    article_content = soup.find('div', class_='td-post-content')

    # Extract article text
    if article_content:
        paragraphs = article_content.find_all('p')
        article_text = "\n".join([p.get_text() for p in paragraphs])

        # Extract URL_ID for filename
        url_id = url.split('/')[-2]
        file_name = f"{url_id}.txt"

        # Save the article text to a text file
        file_path = os.path.join(output_directory, file_name)
        with open(file_path, 'w', encoding='utf-8') as file:
            file.write(article_text)
        print(f"Saved article from {url} to {file_path}")
    else:
        print(f"Article content not found for {url}")

import os
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
nltk.download('punkt')

def read_file_to_string(file_path):
    with open(file_path, 'r', encoding='utf-8') as file:
        file_contents = file.read()
    return file_contents

# Load stopwords from the provided stopwords text file
stopwords_file_path = 'stopwords.txt'  # Replace with the path to your stopwords file
with open(stopwords_file_path, 'r', encoding='utf-8') as stopwords_file:
    custom_stopwords = set(stopwords_file.read().splitlines())

# Load positive words from the provided positive words text file
positive_words_file_path = '/content/positive-words.txt'  # Replace with the path to your positive words file
with open(positive_words_file_path, 'r', encoding='utf-8') as positive_words_file:
    positive_words = set(positive_words_file.read().splitlines())

# Load negative words from the provided negative words text file
negative_words_file_path = '/content/negative-words.txt'  # Replace with the path to your negative words file
with open(negative_words_file_path, 'r', encoding='ISO-8859-1') as negative_words_file:
    negative_words = set(negative_words_file.read().splitlines())

# Create a directory containing the text files
input_directory = "scraped_data"

# Get the list of stopwords from NLTK
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

# Combine NLTK stopwords with custom stopwords
combined_stopwords = stop_words.union(custom_stopwords)

# Loop through each file in the directory
for file_name in os.listdir(input_directory):
    if file_name.endswith(".txt"):
        file_path = os.path.join(input_directory, file_name)

        # Read the content of the file
        with open(file_path, 'r', encoding='utf-8') as file:
            content = file.read()

        # Tokenize the content into words
        words = word_tokenize(content)

        # Remove custom stopwords from the tokenized words
        filtered_words = [word for word in words if word.lower() not in combined_stopwords]

        # Join the filtered words back into a string
        filtered_content = " ".join(filtered_words)

        # Write the filtered content back to the file
        with open(file_path, 'w', encoding='utf-8') as file:
            file.write(filtered_content)

        print(f"Custom stopwords removed from {file_name}")

    # Read the filtered content and print it as a string
    filtered_content_as_string = read_file_to_string(file_path)
    print("Filtered Content as String:", filtered_content_as_string)

    # Perform additional analysis using positive and negative words
    positive_word_count = sum(1 for word in words if word.lower() in positive_words)
    negative_word_count = sum(1 for word in words if word.lower() in negative_words)
    print(f"Positive word count: {positive_word_count}")
    print(f"Negative word count: {negative_word_count}")

print("Custom stopwords removed from all files.")

import os
import nltk
import string
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.corpus import stopwords

nltk.download('punkt')

# Function to calculate syllable count
def syllable_count(word):
    vowels = "AEIOUYaeiouy"
    count = 0
    if len(word) == 0:
        return 0

    if word[0] in vowels:
        count += 1

    for index in range(1, len(word)):
        if word[index] in vowels and word[index - 1] not in vowels:
            count += 1

    if word.endswith("e"):
        count -= 1
    if count == 0:
        count = 1
    return count

# Function to analyze readability
def analyze_readability(words, sentences):
    word_count = len(words)
    sentence_count = len(sentences)

    average_sentence_length = word_count / sentence_count

    complex_word_count = sum(1 for word in words if syllable_count(word) > 2)
    percentage_complex_words = (complex_word_count / word_count) * 100

    fog_index = 0.4 * (average_sentence_length + percentage_complex_words)

    average_words_per_sentence = word_count / sentence_count

    return average_sentence_length, percentage_complex_words, fog_index, average_words_per_sentence

# Load positive and negative words
positive_words = set(open('positive-words.txt', 'r').read().splitlines())
negative_words = set(open('negative-words.txt', 'r',encoding = 'ISO-8859-1').read().splitlines())

# Load stopwords
stop_words = set(stopwords.words('english'))

# Loop through each file in the directory
input_directory = "scraped_data"
output_directory = "analyzed_data"

for file_name in os.listdir(input_directory):
    if file_name.endswith(".txt"):
        file_path = os.path.join(input_directory, file_name)
        output_file_path = os.path.join(output_directory, file_name)

        # Read the content of the file
        with open(file_path, 'r', encoding='utf-8') as file:
            content = file.read()

        # Tokenize the content into words
        words = word_tokenize(content)
        sentences = sent_tokenize(content)

        # Remove punctuation and convert to lowercase
        cleaned_words = [word.lower() for word in words if word not in string.punctuation]

        # Remove stopwords
        filtered_words = [word for word in cleaned_words if word not in stop_words]

        # Sentiment analysis
        positive_score = sum(1 for word in filtered_words if word in positive_words)
        negative_score = sum(1 for word in filtered_words if word in negative_words)
        polarity_score = (positive_score - negative_score) / ((positive_score + negative_score) + 0.000001)
        subjectivity_score = (positive_score + negative_score) / (len(filtered_words) + 0.000001)

        # Readability analysis
        average_sentence_length, percentage_complex_words, fog_index, average_words_per_sentence = analyze_readability(filtered_words, sentences)

        # Print or save the analysis results as needed
        print(f"File: {file_name}")
        print(f"Sentiment Analysis:")
        print(f"Positive Score: {positive_score}")
        print(f"Negative Score: {negative_score}")
        print(f"Polarity Score: {polarity_score}")
        print(f"Subjectivity Score: {subjectivity_score}")
        print(f"Readability Analysis:")
        print(f"Average Sentence Length: {average_sentence_length}")
        print(f"Percentage of Complex Words: {percentage_complex_words}")
        print(f"Fog Index: {fog_index}")
        print(f"Average Words Per Sentence: {average_words_per_sentence}")
        print("------------------------")